"""empty message

Revision ID: 74265cc6cd1c
Revises: e7f7b60977c8
Create Date: 2016-02-29 18:18:18.604093

"""

# revision identifiers, used by Alembic.
revision = '74265cc6cd1c'
down_revision = 'e7f7b60977c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
