"""empty message

Revision ID: 7b29f768a051
Revises: de5ec802a9d3
Create Date: 2016-02-29 18:38:13.513397

"""

# revision identifiers, used by Alembic.
revision = '7b29f768a051'
down_revision = 'de5ec802a9d3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('image', sa.String(length=50), nullable=True),
    sa.Column('fname', sa.String(length=40), nullable=True),
    sa.Column('lname', sa.String(length=40), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=6), nullable=True),
    sa.Column('highscore', sa.Integer(), nullable=True),
    sa.Column('tdollars', sa.Integer(), nullable=True),
    sa.Column('datejoined', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fname', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('lname', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sex', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('highscore', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tdollars', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('datejoined', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'user_pkey'),
    sa.UniqueConstraint('email', name=u'user_email_key'),
    sa.UniqueConstraint('username', name=u'user_username_key')
    )
    op.drop_table('user_info')
    ### end Alembic commands ###
