"""empty message

Revision ID: de5ec802a9d3
Revises: 74265cc6cd1c
Create Date: 2016-02-29 18:31:19.119692

"""

# revision identifiers, used by Alembic.
revision = 'de5ec802a9d3'
down_revision = '74265cc6cd1c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
